### ISSUE TITLE
fix splits entry splitsConfigId (set to sender, instead of receiver)

### ISSUE THREAD

**Issue by evvvritt** [gh0stwheel/drips-subgraph-mainnet-v2#6]
splits entry config id is using receiver when it should be using sender:
https://github.com/gh0stwheel/drips-subgraph-mainnet-v2/blob/8060947b6e5af4bd4d304a5b845d7bd20aaa55fe/src/mapping.ts#L126

**Comment by gh0stwheel** [comment]
Fixed by this PR from @evvvritt 

https://github.com/gh0stwheel/drips-subgraph-mainnet-v2/pull/8
