### ISSUE TITLE
drips has entry of project dripping to itself? (mumbai)

### ISSUE THREAD

**Issue by evvvritt** [gh0stwheel/drips-subgraph-mainnet-v2#7]
it's the same amount as an NFT I bought on that project, so maybe something's tangled around minting?

<img width="1143" alt="Screen Shot 2022-02-06 at 10 56 52 PM" src="https://user-images.githubusercontent.com/6071219/152703139-ed569608-0d28-468f-a804-92f101c9c1af.png">
<img width="894" alt="Screen Shot 2022-02-06 at 10 55 25 PM" src="https://user-images.githubusercontent.com/6071219/152703144-a2f51619-2e0a-4f44-bb1f-e12b920d912d.png">

**Comment by gh0stwheel** [comment]
this is actually technically correct, since the communities are implemented as ERC-721s that are technically dripping to themselves.

with that said, for now we've removed these entries in the subgraph.
